### PR TITLE
Improve versioning of built APK

### PR DESCRIPTION
**Pull request by litetex**
Include current version id/number inside version name and code for better identification

> I'm currently experimenting with the [Nightly](https://github.com/TeamNewPipe/NewPipe-nightly) and how to get it into an F-Droid repo.
> So far it looks quite good however all nightly builds have the same version and name which confuses F-Droid.
>
> <details><summary>Example</summary>
> 
> 
> 
> </details>

More details in https://github.com/TeamNewPipe/NewPipe/pull/11656

### CODE REVIEW

**Comment by TobiGr** [comment]
After merging this PR one will not be able to update from an older nightly because the version code will be lower. We need to communicate this in the release notes of the first affected nightly and add tell the testers to backup and restore their data.

**Comment by litetex** [comment]
> After merging this PR one will not be able to update from an older nightly because the version code will be lower. We need to communicate this in the release notes of the first affected nightly and add tell the testers to backup and restore their data.

Good point.
We could maybe manually create a tag called ``nightly-1000`` so that the version is above the currently set ``999``.

**Review by TobiGr — APPROVED** [review]
LGTM

**Comment by litetex** [comment]
Merging now, we will see if the new system works

**Comment by litetex** [comment]
Looks good :D

**Comment by Stypox** [comment]
How do you obtain an F-Droid repository?

**Comment by litetex** [comment]
> How do you obtain an F-Droid repository?

I'm still experimenting with this but basically it works like this:
1. Get [f-droid tools](https://f-droid.org/en/docs/Installing_the_Server_and_Repo_Tools/) (currently released tools are broken and current Docker image is not working) and configure them
2. Get APKs (maybe with an automated script)
3. Run ``fdroid update && fdroid deploy``
4. Profit!

See also: https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/#overview

I will try do some further testing in the next time and post updates here or on our matrix channel.

**Comment by Stypox** [comment]
Oh okok, I thought you set up the client to load the APKs directly from github or something ;-)

**Pull request merged**
